### PR TITLE
Updated data table colors and font

### LINKED ISSUE #141: Data Table is not using theme correctly
#### Describe the bug / expected behavior
I don't think the data table is using Brightlayer UI theme correctly. The font is incorrect, and the font color for table header is too light. 
image
image

From https://github.com/etn-ccis/blui-react-native-themes/issues/57

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #141 BLUI-5008

#### Changes proposed in this Pull Request:

- Updated color and fonts of Data table title

#### Screenshots / Screen Recording (if applicable)

Simulator Screenshot - iphone 12 pro - 2023-12-14 at 14 19 56

#### To Test:

- yarn ios

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by jvgreiner** [comment]
looks good using label large. Do we know why pagination using primary for color here?

image

**Comment by huayunh** [comment]
Can we fix this in our themes instead?

**Comment by ektaghag-eaton** [comment]
> looks good using label large. Do we know why pagination using primary for color here?
> 
> image

As per https://brightlayer-ui.github.io/patterns/tables pagination is not in primary color but **back** and **previous** colors are in primary.

**Comment by surajeaton** [comment]
Submitted a bug on react native paper github. Also added a jira story to add readme for external dependencies issues.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
