### PR TITLE
Update to react native version 0.64.0

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Update all dependencies to use RN 64
- Had to follow the manual upgrade instructions...not fun

### CODE REVIEW

**Comment by joebochill** [comment]
Did this to confirm a bug in react-native using the latest version and figured I might as well commit it.

**Comment by daileytj** [comment]
This looks good on Android. 

I'm having a hard time getting this running locally for iOS. I first had to upgrade my local cocoapods from 1.10.0 to 1.10.1. I'm currently stuck with the following error when trying to install pods though.

Screen Shot 2021-03-22 at 9 44 31 AM

**Comment by jeffvg** [comment]
> This looks good on Android.
> 
> I'm having a hard time getting this running locally for iOS. I first had to upgrade my local cocoapods from 1.10.0 to 1.10.1. I'm currently stuck with the following error when trying to install pods though.
> 
> Screen Shot 2021-03-22 at 9 44 31 AM

I'm having issues too. Need to look at dev branch but this feature branch giving me this..

Launching iPhone 12 (iOS 14.4)
info Building (using "xcodebuild -workspace reactNativeShowcaseDemo.xcworkspace -configuration Debug -scheme reactNativeShowcaseDemo -destination id=E184973B-58AD-4EB3-9C56-E3634560B974")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening reactNativeShowcaseDemo.xcworkspace.

**Comment by joebochill** [comment]
> This looks good on Android.
> 
> I'm having a hard time getting this running locally for iOS. I first had to upgrade my local cocoapods from 1.10.0 to 1.10.1. I'm currently stuck with the following error when trying to install 

I did have to update my Pod repo and reinstall the pods after upgrading to RN64...did you run the `pod repo update` that it suggested?

**Comment by joebochill** [comment]
> I'm having issues too. Need to look at dev branch but this feature branch giving me this..
> 
> Launching iPhone 12 (iOS 14.4)
> info Building (using "xcodebuild -workspace reactNativeShowcaseDemo.xcworkspace -configuration Debug -scheme reactNativeShowcaseDemo -destination id=E184973B-58AD-4EB3-9C56-E3634560B974")
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening reactNativeShowcaseDemo.xcworkspace.

Do you have an iphone 12 simulator set up in xCode?

**Comment by jeffvg** [comment]
So I went ahead and did pod install in ios directory and had an update related to this script phase.
https://guides.cocoapods.org/syntax/podspec.html#script_phases
Before pod install the build would fail right away and now with this update, I build but get screen of red death. 

(unhandled JS Exception Super expression must be null or a function)

image

https://github.com/facebook/react-native/issues/28423
still reading other threads

**Comment by daileytj** [comment]
> > This looks good on Android.
> > I'm having a hard time getting this running locally for iOS. I first had to upgrade my local cocoapods from 1.10.0 to 1.10.1. I'm currently stuck with the following error when trying to install
> 
> I did have to update my Pod repo and reinstall the pods after upgrading to RN64...did you run the `pod repo update` that it suggested?

🙄  I skimmed right past that! It's running fine now... APPROVED!

**Review by daileytj — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]
looks good on both iOS/Android....Pod repo install / pod install fixed me up

**Pull request merged**
