### PR TITLE
Fix background color for elevated button

### LINKED ISSUE #167: Elevated button wrong background color
#### Describe the bug / expected behavior

The background color of default "elevated" buttons is incorrect.

image

image

#### Suggested fix

Expecting "surface container low". The button looks like "surface container lowest"

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 5085 .

#### Changes proposed in this Pull Request:

- Used buttonColor prop to match figma design for elevated button
- Fixed [75](https://github.com/etn-ccis/blui-react-native-showcase-demo/issues/167)
-

#### Screenshots / Screen Recording (if applicable)

- 
Screenshot 2023-12-28 at 11 20 00 PM
Screenshot 2023-12-28 at 11 20 10 PM

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — APPROVED** [review]

**Comment by huayunh** [comment]
@ektaghag-eaton have you reported the issue to RNP?

**Comment by ektaghag-eaton** [comment]
> @ektaghag-eaton have you reported the issue to RNP?

Why? I was able to fix this issue with the buttonColor prop.

**Comment by huayunh** [comment]
@ektaghag-eaton If RNP was coloring their buttons correctly, then we shouldn't need to do any of these in the first place. We agreed, during the planning / grooming, that for issues beyond control of Brightlayer UI (ie, cannot be corrected by changing themes or RN component lib), we:
(1) Fix it in the showcase
(2) Document it for adopters to follow
(3) Report to RNP by logging an issue (or if something has already been reported, make a comment in the issue)

**Comment by huayunh** [comment]
I just checked RNP's documentation. [Their screenshot](https://callstack.github.io/react-native-paper/docs/components/Button/) for a `mode="elevated"` looks correct to me (i.e., their buttons are not pure white, but with some tonal gray background to it). Why is our showcase looking incorrect?

**Comment by ektaghag-eaton** [comment]
> I just checked RNP's documentation. [Their screenshot](https://callstack.github.io/react-native-paper/docs/components/Button/) for a `mode="elevated"` looks correct to me (i.e., their buttons are not pure white, but with some tonal gray background to it). Why is our showcase looking incorrect?

https://github.com/callstack/react-native-paper/blob/main/src/components/Button/utils.tsx#L65 Here RNP is using `theme.colors.elevation.level1`. and as per our design theme.colors.elevation.level1 (Surface Container Lowest). 
https://github.com/etn-ccis/blui-react-native-themes/blob/dev/src/blueTheme.ts#L53. I think we need to recheck our theme colors for elevation.

Screenshot 2024-01-01 at 7 36 38 PM

**Comment by huayunh** [comment]
Ok, thanks for checking. I think React Native Paper is using the old "surface color overlay" method, which [has been deprecated by Material Design since March 2023.](https://m3.material.io/styles/elevation/applying-elevation#c7b7a13e-5867-4a01-8728-d0a950fce5b3) 

The [current Material Design design specs](https://m3.material.io/components/buttons/specs) call explicitly for "surface container low" for background color of elevated buttons. 

I think this is one other reason to request React Native Paper to dump the `elevation` object and match with the latest theme structure from Material Design (i.e., the "surface container low" colors).

**Pull request merged**
